// Tokamak Arcade reuses the contract addresses generated by scripts/arcade.sh.
// Re-exporting keeps this UI in lockstep with the devnet deployment without
// needing the script to know about a second arcade directory.
export { CONFIG } from '../../arcade/shared/config.js';
