[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
remappings = [
  "interfaces/=../optimism/packages/contracts-bedrock/interfaces/",
  "optimism/=../optimism/packages/contracts-bedrock/",
]
