// Template for arcade/shared/config.js.
// Do NOT edit this file directly — scripts/arcade.sh writes config.js
// with freshly deployed addresses on every run. Copy this to config.js
// if you are wiring the arcade to your own deployment instead.
export const CONFIG = {
  chainId:     13374,
  rpc:         'http://localhost:8545',
  vrfAddress:  '0x42000000000000000000000000000000000000f0',
  flip:        '0x0000000000000000000000000000000000000000',
  dice:        '0x0000000000000000000000000000000000000000',
  plinko:      '0x0000000000000000000000000000000000000000',
  lottery:     '0x0000000000000000000000000000000000000000',
  jankenman:   '0x0000000000000000000000000000000000000000',
};
