// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: vrf-enclave/proto/vrf_enclave.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          []byte                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"` // 32-byte VRF seed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveRequest) Reset() {
	*x = ProveRequest{}
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveRequest) ProtoMessage() {}

func (x *ProveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveRequest.ProtoReflect.Descriptor instead.
func (*ProveRequest) Descriptor() ([]byte, []int) {
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP(), []int{0}
}

func (x *ProveRequest) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type ProveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beta          []byte                 `protobuf:"bytes,1,opt,name=beta,proto3" json:"beta,omitempty"` // 32-byte VRF output
	Pi            []byte                 `protobuf:"bytes,2,opt,name=pi,proto3" json:"pi,omitempty"`     // 81-byte VRF proof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveResponse) Reset() {
	*x = ProveResponse{}
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveResponse) ProtoMessage() {}

func (x *ProveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveResponse.ProtoReflect.Descriptor instead.
func (*ProveResponse) Descriptor() ([]byte, []int) {
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP(), []int{1}
}

func (x *ProveResponse) GetBeta() []byte {
	if x != nil {
		return x.Beta
	}
	return nil
}

func (x *ProveResponse) GetPi() []byte {
	if x != nil {
		return x.Pi
	}
	return nil
}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP(), []int{2}
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 33-byte compressed secp256k1 public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetAttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"` // optional freshness nonce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationRequest) Reset() {
	*x = GetAttestationRequest{}
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationRequest) ProtoMessage() {}

func (x *GetAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationRequest.ProtoReflect.Descriptor instead.
func (*GetAttestationRequest) Descriptor() ([]byte, []int) {
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttestationRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type GetAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        []byte                 `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`                        // platform-specific attestation report (e.g. SGX quote)
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 33-byte public key bound to the attestation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationResponse) Reset() {
	*x = GetAttestationResponse{}
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationResponse) ProtoMessage() {}

func (x *GetAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vrf_enclave_proto_vrf_enclave_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationResponse.ProtoReflect.Descriptor instead.
func (*GetAttestationResponse) Descriptor() ([]byte, []int) {
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttestationResponse) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GetAttestationResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_vrf_enclave_proto_vrf_enclave_proto protoreflect.FileDescriptor

const file_vrf_enclave_proto_vrf_enclave_proto_rawDesc = "" +
	"\n" +
	"#vrf-enclave/proto/vrf_enclave.proto\x12\n" +
	"vrfenclave\"\"\n" +
	"\fProveRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\fR\x04seed\"3\n" +
	"\rProveResponse\x12\x12\n" +
	"\x04beta\x18\x01 \x01(\fR\x04beta\x12\x0e\n" +
	"\x02pi\x18\x02 \x01(\fR\x02pi\"\x15\n" +
	"\x13GetPublicKeyRequest\"5\n" +
	"\x14GetPublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\"5\n" +
	"\x15GetAttestationRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"O\n" +
	"\x16GetAttestationResponse\x12\x16\n" +
	"\x06report\x18\x01 \x01(\fR\x06report\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey2\xf6\x01\n" +
	"\n" +
	"VRFEnclave\x12<\n" +
	"\x05Prove\x12\x18.vrfenclave.ProveRequest\x1a\x19.vrfenclave.ProveResponse\x12Q\n" +
	"\fGetPublicKey\x12\x1f.vrfenclave.GetPublicKeyRequest\x1a .vrfenclave.GetPublicKeyResponse\x12W\n" +
	"\x0eGetAttestation\x12!.vrfenclave.GetAttestationRequest\x1a\".vrfenclave.GetAttestationResponseB<Z:github.com/tokamak-network/enshrined-vrf/vrf-enclave/protob\x06proto3"

var (
	file_vrf_enclave_proto_vrf_enclave_proto_rawDescOnce sync.Once
	file_vrf_enclave_proto_vrf_enclave_proto_rawDescData []byte
)

func file_vrf_enclave_proto_vrf_enclave_proto_rawDescGZIP() []byte {
	file_vrf_enclave_proto_vrf_enclave_proto_rawDescOnce.Do(func() {
		file_vrf_enclave_proto_vrf_enclave_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vrf_enclave_proto_vrf_enclave_proto_rawDesc), len(file_vrf_enclave_proto_vrf_enclave_proto_rawDesc)))
	})
	return file_vrf_enclave_proto_vrf_enclave_proto_rawDescData
}

var file_vrf_enclave_proto_vrf_enclave_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vrf_enclave_proto_vrf_enclave_proto_goTypes = []any{
	(*ProveRequest)(nil),           // 0: vrfenclave.ProveRequest
	(*ProveResponse)(nil),          // 1: vrfenclave.ProveResponse
	(*GetPublicKeyRequest)(nil),    // 2: vrfenclave.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),   // 3: vrfenclave.GetPublicKeyResponse
	(*GetAttestationRequest)(nil),  // 4: vrfenclave.GetAttestationRequest
	(*GetAttestationResponse)(nil), // 5: vrfenclave.GetAttestationResponse
}
var file_vrf_enclave_proto_vrf_enclave_proto_depIdxs = []int32{
	0, // 0: vrfenclave.VRFEnclave.Prove:input_type -> vrfenclave.ProveRequest
	2, // 1: vrfenclave.VRFEnclave.GetPublicKey:input_type -> vrfenclave.GetPublicKeyRequest
	4, // 2: vrfenclave.VRFEnclave.GetAttestation:input_type -> vrfenclave.GetAttestationRequest
	1, // 3: vrfenclave.VRFEnclave.Prove:output_type -> vrfenclave.ProveResponse
	3, // 4: vrfenclave.VRFEnclave.GetPublicKey:output_type -> vrfenclave.GetPublicKeyResponse
	5, // 5: vrfenclave.VRFEnclave.GetAttestation:output_type -> vrfenclave.GetAttestationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vrf_enclave_proto_vrf_enclave_proto_init() }
func file_vrf_enclave_proto_vrf_enclave_proto_init() {
	if File_vrf_enclave_proto_vrf_enclave_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vrf_enclave_proto_vrf_enclave_proto_rawDesc), len(file_vrf_enclave_proto_vrf_enclave_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vrf_enclave_proto_vrf_enclave_proto_goTypes,
		DependencyIndexes: file_vrf_enclave_proto_vrf_enclave_proto_depIdxs,
		MessageInfos:      file_vrf_enclave_proto_vrf_enclave_proto_msgTypes,
	}.Build()
	File_vrf_enclave_proto_vrf_enclave_proto = out.File
	file_vrf_enclave_proto_vrf_enclave_proto_goTypes = nil
	file_vrf_enclave_proto_vrf_enclave_proto_depIdxs = nil
}
