// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: vrf-enclave/proto/vrf_enclave.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VRFEnclave_Prove_FullMethodName          = "/vrfenclave.VRFEnclave/Prove"
	VRFEnclave_GetPublicKey_FullMethodName   = "/vrfenclave.VRFEnclave/GetPublicKey"
	VRFEnclave_GetAttestation_FullMethodName = "/vrfenclave.VRFEnclave/GetAttestation"
)

// VRFEnclaveClient is the client API for VRFEnclave service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VRFEnclave runs inside a TEE. The secret key never leaves the enclave.
type VRFEnclaveClient interface {
	// Prove generates a VRF proof for the given seed.
	Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error)
	// GetPublicKey returns the compressed secp256k1 public key (33 bytes).
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
	// GetAttestation returns a remote attestation report that proves
	// the enclave is running the expected code and holds the key.
	GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error)
}

type vRFEnclaveClient struct {
	cc grpc.ClientConnInterface
}

func NewVRFEnclaveClient(cc grpc.ClientConnInterface) VRFEnclaveClient {
	return &vRFEnclaveClient{cc}
}

func (c *vRFEnclaveClient) Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponse)
	err := c.cc.Invoke(ctx, VRFEnclave_Prove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vRFEnclaveClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, VRFEnclave_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vRFEnclaveClient) GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttestationResponse)
	err := c.cc.Invoke(ctx, VRFEnclave_GetAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VRFEnclaveServer is the server API for VRFEnclave service.
// All implementations must embed UnimplementedVRFEnclaveServer
// for forward compatibility.
//
// VRFEnclave runs inside a TEE. The secret key never leaves the enclave.
type VRFEnclaveServer interface {
	// Prove generates a VRF proof for the given seed.
	Prove(context.Context, *ProveRequest) (*ProveResponse, error)
	// GetPublicKey returns the compressed secp256k1 public key (33 bytes).
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	// GetAttestation returns a remote attestation report that proves
	// the enclave is running the expected code and holds the key.
	GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error)
	mustEmbedUnimplementedVRFEnclaveServer()
}

// UnimplementedVRFEnclaveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVRFEnclaveServer struct{}

func (UnimplementedVRFEnclaveServer) Prove(context.Context, *ProveRequest) (*ProveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prove not implemented")
}
func (UnimplementedVRFEnclaveServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedVRFEnclaveServer) GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttestation not implemented")
}
func (UnimplementedVRFEnclaveServer) mustEmbedUnimplementedVRFEnclaveServer() {}
func (UnimplementedVRFEnclaveServer) testEmbeddedByValue()                    {}

// UnsafeVRFEnclaveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VRFEnclaveServer will
// result in compilation errors.
type UnsafeVRFEnclaveServer interface {
	mustEmbedUnimplementedVRFEnclaveServer()
}

func RegisterVRFEnclaveServer(s grpc.ServiceRegistrar, srv VRFEnclaveServer) {
	// If the following call pancis, it indicates UnimplementedVRFEnclaveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VRFEnclave_ServiceDesc, srv)
}

func _VRFEnclave_Prove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VRFEnclaveServer).Prove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VRFEnclave_Prove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VRFEnclaveServer).Prove(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VRFEnclave_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VRFEnclaveServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VRFEnclave_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VRFEnclaveServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VRFEnclave_GetAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VRFEnclaveServer).GetAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VRFEnclave_GetAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VRFEnclaveServer).GetAttestation(ctx, req.(*GetAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VRFEnclave_ServiceDesc is the grpc.ServiceDesc for VRFEnclave service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VRFEnclave_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vrfenclave.VRFEnclave",
	HandlerType: (*VRFEnclaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prove",
			Handler:    _VRFEnclave_Prove_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _VRFEnclave_GetPublicKey_Handler,
		},
		{
			MethodName: "GetAttestation",
			Handler:    _VRFEnclave_GetAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vrf-enclave/proto/vrf_enclave.proto",
}
